<script language="JavaScript" type="text/JavaScript">
<!--
function Social_Load() { var d=document; if(d.images){ if(!d.Social) d.Social=new Array();
var i,j=d.Social.length,a=Social_Load.arguments; for(i=0; i<a.length; i++)
if (a[i].indexOf("#")!=0){ d.Social[j]=new Image; d.Social[j++].src=a[i];}}
}
Social_Load('http://www.social-bookmark-script.de/img/bookmarks/digg_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/del_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/reddit_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/simpy_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/stumbleupon_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/slashdot_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/netscape_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/furl_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/yahoo_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/spurl_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/google_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/blinklist_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/blogmarks_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/diigo_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/technorati_trans_ani.gif','http://www.social-bookmark-script.de/img/bookmarks/blinkbits_trans_ani.gif','http://www.social-bookmark-script.de/load.gif')
function schnipp() { var i,x,a=document.MM_sr; for(i=0;a&&i<a.length&&(x=a[i])&&x.oSrc;i++) x.src=x.oSrc;
}
function schnupp(n, d) { var p,i,x; if(!d) d=document; if((p=n.indexOf("?"))>0&&parent.frames.length) {
d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}
if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];
for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=schnupp(n,d.layers[i].document);
if(!x && d.getElementById) x=d.getElementById(n); return x;
}
function schnapp() { var i,j=0,x,a=schnapp.arguments; document.MM_sr=new Array; for(i=0;i<(a.length-2);i+=3)
if ((x=schnupp(a[i]))!=null){document.MM_sr[j++]=x; if(!x.oSrc) x.oSrc=x.src; x.src=a[i+2];}
}
//-->
</script>
<li><a rel="nofollow" style="text-decoration: none;" href="http://digg.com/" onclick="window.open('http://digg.com/submit?phase=2&url='+encodeURIComponent(location.href)+'&bodytext=&tags=&title='+encodeURIComponent(document.title));return false;" title="Add to: Digg" onmouseover="schnapp('Digg','','share/images/common_files/digg_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/digg_trans.gif" alt="Add to: Digg" name="Digg" id="Digg" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://del.icio.us/" onclick="window.open('http://del.icio.us/post?v=2&url='+encodeURIComponent(location.href)+'&notes=&tags=&title='+encodeURIComponent(document.title));return false;" title="Add to: Del.icio.us" onmouseover="schnapp('Delicious','','share/images/common_files/del_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/del_trans.gif" alt="Add to: Del.icio.us" name="Delicious" id="Delicious" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://reddit.com/" onclick="window.open('http://reddit.com/submit?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title));return false;" title="Add to: Reddit" onmouseover="schnapp('Reddit','','share/images/common_files/reddit_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/reddit_trans.gif" alt="Add to: Reddit" name="Reddit" id="Reddit" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.simpy.com/" onclick="window.open('http://www.simpy.com/simpy/LinkAdd.do?title='+encodeURIComponent(document.title)+'&tags=&note=&href='+encodeURIComponent(location.href));return false;" title="Add to: Simpy" onmouseover="schnapp('Simpy','','share/images/common_files/simpy_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/simpy_trans.gif" alt="Add to: Simpy" name="Simpy" id="Simpy" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.stumbleupon.com/" onclick="window.open('http://www.stumbleupon.com/submit?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title));return false;" title="Add to: StumbleUpon" onmouseover="schnapp('StumbleUpon','','share/images/common_files/stumbleupon_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/stumbleupon_trans.gif" alt="Add to: StumbleUpon" name="StumbleUpon" id="StumbleUpon" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://slashdot.org/" onclick="window.open('http://slashdot.org/bookmark.pl?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title));return false;" title="Add to: Slashdot" onmouseover="schnapp('Slashdot','','share/images/common_files/slashdot_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/slashdot_trans.gif" alt="Add to: Slashdot" name="Slashdot" id="Slashdot" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.netscape.com/" onclick="window.open('http://www.netscape.com/submit/?U='+encodeURIComponent(location.href)+'&T='+encodeURIComponent(document.title));return false;" title="Add to: Netscape" onmouseover="schnapp('Netscape','','share/images/common_files/netscape_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/netscape_trans.gif" alt="Add to: Netscape" name="Netscape" id="Netscape" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.furl.net/" onclick="window.open('http://www.furl.net/storeIt.jsp?u='+encodeURIComponent(location.href)+'&keywords=&t='+encodeURIComponent(document.title));return false;" title="Add to: Furl" onmouseover="schnapp('Furl','','share/images/common_files/furl_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/furl_trans.gif" alt="Add to: Furl" name="Furl" id="Furl" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.yahoo.com/" onclick="window.open('http://myweb2.search.yahoo.com/myresults/bookmarklet?t='+encodeURIComponent(document.title)+'&d=&tag=&u='+encodeURIComponent(location.href));return false;" title="Add to: Yahoo" onmouseover="schnapp('Yahoo','','share/images/common_files/yahoo_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/yahoo_trans.gif" alt="Add to: Yahoo" name="Yahoo" id="Yahoo" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.spurl.net/" onclick="window.open('http://www.spurl.net/spurl.php?v=3&tags=&title='+encodeURIComponent(document.title)+'&url='+encodeURIComponent(document.location.href));return false;" title="Add to: Spurl" onmouseover="schnapp('Spurl','','share/images/common_files/spurl_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/spurl_trans.gif" alt="Add to: Spurl" name="Spurl" id="Spurl" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.google.com/" onclick="window.open('http://www.google.com/bookmarks/mark?op=add&hl=en&bkmk='+encodeURIComponent(location.href)+'&annotation=&labels=&title='+encodeURIComponent(document.title));return false;" title="Add to: Google" onmouseover="schnapp('Google','','share/images/common_files/google_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/google_trans.gif" alt="Add to: Google" name="Google" id="Google" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.blinklist.com/" onclick="window.open('http://www.blinklist.com/index.php?Action=Blink/addblink.php&Description=&Tag=&Url='+encodeURIComponent(location.href)+'&Title='+encodeURIComponent(document.title));return false;" title="Add to: Blinklist" onmouseover="schnapp('Blinklist','','share/images/common_files/blinklist_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/blinklist_trans.gif" alt="Add to: Blinklist" name="Blinklist" id="Blinklist" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://blogmarks.net/" onclick="window.open('http://blogmarks.net/my/new.php?mini=1&simple=1&url='+encodeURIComponent(location.href)+'&content=&public-tags=&title='+encodeURIComponent(document.title));return false;" title="Add to: Blogmarks" onmouseover="schnapp('Blogmarks','','share/images/common_files/blogmarks_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/blogmarks_trans.gif" alt="Add to: Blogmarks" name="Blogmarks" id="Blogmarks" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.diigo.com/" onclick="window.open('http://www.diigo.com/post?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)+'&tag=&comments='); return false;" title="Add to: Diigo" onmouseover="schnapp('Diigo','','share/images/common_files/diigo_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/diigo_trans.gif" alt="Add to: Diigo" name="Diigo" id="Diigo" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.technorati.com/" onclick="window.open('http://technorati.com/faves?add='+encodeURIComponent(location.href)+'&tag=');return false;" title="Add to: Technorati" onmouseover="schnapp('Technorati','','share/images/common_files/technorati_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/technorati_trans.gif" alt="Add to: Technorati" name="Technorati" id="Technorati" border="0"></a></li>
<li><a rel="nofollow" style="text-decoration: none;" href="http://www.blinkbits.com/" onclick="window.open('http://www.blinkbits.com/bookmarklets/save.php?v=1&title='+encodeURIComponent(document.title)+'&source_url='+encodeURIComponent(location.href)+'&source_image_url=&rss_feed_url=&rss_feed_url=&rss2member=&body=');return false;" title="Add to: Blinkbits" onmouseover="schnapp('Blinkbits','','share/images/common_files/blinkbits_trans_ani.gif',1)" onmouseout="schnipp()"> <img style="padding-bottom: 1px;" src="share/images/common_files/blinkbits_trans.gif" alt="Add to: Blinkbits" name="Blinkbits" id="Blinkbits" border="0"></a></li>